services:
  - type: web
    name: cracked
    env: node
    buildCommand: cd client && npm install --legacy-peer-deps && npm run build && cd .. && npm install --legacy-peer-deps
    startCommand: npx ts-node --esm server.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
