services:
  - type: web
    name: cracked
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install --legacy-peer-deps && cd ..
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://cracked1-1.onrender.com
